version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: devvault-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: devvault
    ports:
      - "5432:5432"
    volumes:
      - devvault-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  devvault-data:
